version: '3.8'
services:
#  justshake-cocktails-web-service:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: justshake-cocktails-web:1.0.0
#    container_name: justshake-cocktails-web
#    ports:
#      - "2000:80"
#    depends_on:
#      - justshake-cocktails-db
#    volumes:
#      - ./.compose/justshake-cocktails-web/secret-config.yml:/app/config/secret-config.yml
#    environment:
#      - HTTP_PORT=80
#      - MONGO_CONNECTION_STRING=mongodb://justshake-cocktails-db:27017
#      - MONGO_DATABASE=justshake
#    networks:
#      - justsquad

  justshake-cocktails-db:
    image: mongo:7.0.2
    container_name: justshake-cocktails-db
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=justshake-cocktails-user
      - MONGODB_INITDB_ROOT_PASSWORD=504811dc-0a7f-4f48-9d63-340060ec909f
      - MONGODB_INITDB_DATABASE=justshake
    volumes:
      - ./.compose/justshake-cocktails-db/data:/data/db
    ports:
      - "27017:27017"
    networks:
      - justsquad

networks:
  justsquad:
    driver: bridge