version: '3.8'
services:
  justshake-cocktails-web-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: justshake-cocktails-web:latest
    container_name: justshake-cocktails-web
    ports:
      - "2000:8080"
    depends_on:
      - justshake-cocktails-db
    volumes:
      - ./justshake-cocktails-web/secret-config.yml:/config/secret-config.yml
    networks:
      - justsquad

  justshake-cocktails-db:
    image: mongo:7.0.2
    container_name: justshake-cocktails-db
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=justshake-cocktails-user
      - MONGODB_INITDB_ROOT_PASSWORD=504811dc-0a7f-4f48-9d63-340060ec909f
      - MONGODB_INITDB_DATABASE=justshake
    volumes:
      - ./.compose/justshake-cocktails-db/data:/data/db
    ports:
      - "27017:27017"
    networks:
      - justsquad

networks:
  justsquad:
    driver: bridge