version: '3.8'
services:
#  justshake-cocktails-web-service:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: justshake-cocktails-web:latest
#    container_name: justshake-cocktails-web
#    ports:
#      - "2000:80"
#    depends_on:
#      - justshake-cocktails-db
#    volumes:
#      - ./justshake-cocktails-web/appsettings.json:/app/appsettings.json
#    networks:
#      - justsquad

  justshake-cocktails-db:
    image: mongo:7.0.2
    container_name: justshake-cocktails-db
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=justshake-cocktails-user
      - MONGODB_INITDB_ROOT_PASSWORD=504811DC-0A7F-4F48-9D63-340060EC909F
      - MONGODB_INITDB_DATABASE=cocktails
    volumes:
      - ./.compose/justshake-cocktails-db/data:/data/db
    ports:
      - "27017:27017"
    networks:
      - justsquad

networks:
  justsquad:
    driver: bridge