# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: release

on:
  push:
    branches: [ "main" ]

jobs:
  check:
    name: Check code
    runs-on: ${{vars.RUNNER_NAME}}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.5'
          
      - name: Update package indexes
        run: sudo apt update

      - name: Install Git
        run: sudo apt install -y git 
      
      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code

      - name: Go Vet
        run: go vet ./...

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

  tests:
    name: tests
    needs: check
    runs-on: ${{vars.RUNNER_NAME}}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.5'

      - name: Test
        run: go test -v ./...

  build:
    name: Build
    needs: check
    runs-on: ${{vars.RUNNER_NAME}}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go  
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.5'

      - name: Go Mod
        run: go mod download

      - name: Go Mod Verify
        run: go mod verify

      - name: Build
        run: go build -v ./...
